---

- name: apt cache updated
  apt: update_cache=True cache_valid_time=86400

- name: ensure basic packages are installed
  apt: pkg={{ item }} state=present
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - python-pip
   - software-properties-common

- name: docker apt key present
  apt_key: id=0EBFCD88 keyserver=keys.gnupg.net state=present

- name: docker apt list present
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' state=present update_cache=true

- name: ensure docker package is installed
  apt: pkg=docker-ce state=present

- name: ensure docker-compose in installed
  pip: name=docker-compose

# GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
- name: ensure cgroup_enable is enabled in kernel
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*cgroup_enable)\"[^\"]+)(\".*)'
    line: '\1 cgroup_enable=memory\2'
  notify:
   - update grub

- name: ensure swapaccount is enabled in kernel
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*swapaccount)\"[^\"]+)(\".*)'
    line: '\1 swapaccount=1\2'
  notify:
   - update grub
